services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_admin -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    # volumes:       # If you would like to persist the database data, uncomment this section
    #   - db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgres://user_admin:secret_password@db:5432/wallet_db
      - JWT_PRIVATE_KEY=ILIACHALLENGE
    depends_on:
      db:
        condition: service_healthy